[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  CI = "false"
  NODE_VERSION = "18"

# Redirect all API calls to backend (optional fallback)
[[redirects]]
  from = "/api/*"
  to = "https://translation-md1a.onrender.com/api/:splat"
  status = 200
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200